// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type SessionStatus string

const (
	SessionStatusPending      SessionStatus = "pending"
	SessionStatusProvisioning SessionStatus = "provisioning"
	SessionStatusReady        SessionStatus = "ready"
	SessionStatusTerminating  SessionStatus = "terminating"
	SessionStatusTerminated   SessionStatus = "terminated"
	SessionStatusError        SessionStatus = "error"
)

func (e *SessionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionStatus(s)
	case string:
		*e = SessionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionStatus: %T", src)
	}
	return nil
}

type NullSessionStatus struct {
	SessionStatus SessionStatus `json:"session_status"`
	Valid         bool          `json:"valid"` // Valid is true if SessionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SessionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionStatus), nil
}

type GpuSku struct {
	Sku         string `json:"sku"`
	Region      string `json:"region"`
	Family      string `json:"family"`
	Vcpu        int32  `json:"vcpu"`
	Gpu         string `json:"gpu"`
	HourlyCents int32  `json:"hourly_cents"`
}

type Session struct {
	ID           string             `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Sku          string             `json:"sku"`
	Region       string             `json:"region"`
	Status       SessionStatus      `json:"status"`
	InstanceID   *string            `json:"instance_id"`
	PublicIp     *string            `json:"public_ip"`
	ErrorReason  *string            `json:"error_reason"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	ReadyAt      pgtype.Timestamptz `json:"ready_at"`
	TerminatedAt pgtype.Timestamptz `json:"terminated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	ClerkSubject string             `json:"clerk_subject"`
	Email        *string            `json:"email"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
