// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, user_id, sku, region, status)
VALUES ($1, $2, $3, $4, 'pending')
RETURNING id, user_id, sku, region, status, instance_id, public_ip, error_reason, created_at, updated_at, ready_at, terminated_at
`

type CreateSessionParams struct {
	ID     string      `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
	Sku    string      `json:"sku"`
	Region string      `json:"region"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.Sku,
		arg.Region,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Sku,
		&i.Region,
		&i.Status,
		&i.InstanceID,
		&i.PublicIp,
		&i.ErrorReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadyAt,
		&i.TerminatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, user_id, sku, region, status, instance_id, public_ip, error_reason, created_at, updated_at, ready_at, terminated_at FROM sessions WHERE id = $1
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Sku,
		&i.Region,
		&i.Status,
		&i.InstanceID,
		&i.PublicIp,
		&i.ErrorReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadyAt,
		&i.TerminatedAt,
	)
	return i, err
}

const getSessionForUser = `-- name: GetSessionForUser :one
SELECT id, user_id, sku, region, status, instance_id, public_ip, error_reason, created_at, updated_at, ready_at, terminated_at FROM sessions WHERE id = $1 AND user_id = $2
`

type GetSessionForUserParams struct {
	ID     string      `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetSessionForUser(ctx context.Context, arg GetSessionForUserParams) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionForUser, arg.ID, arg.UserID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Sku,
		&i.Region,
		&i.Status,
		&i.InstanceID,
		&i.PublicIp,
		&i.ErrorReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadyAt,
		&i.TerminatedAt,
	)
	return i, err
}

const listSessionsForUser = `-- name: ListSessionsForUser :many
SELECT id, user_id, sku, region, status, instance_id, public_ip, error_reason, created_at, updated_at, ready_at, terminated_at FROM sessions WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2
`

type ListSessionsForUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) ListSessionsForUser(ctx context.Context, arg ListSessionsForUserParams) ([]Session, error) {
	rows, err := q.db.Query(ctx, listSessionsForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Sku,
			&i.Region,
			&i.Status,
			&i.InstanceID,
			&i.PublicIp,
			&i.ErrorReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ReadyAt,
			&i.TerminatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSession = `-- name: LockSession :one
SELECT id, user_id, sku, region, status, instance_id, public_ip, error_reason, created_at, updated_at, ready_at, terminated_at FROM sessions WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRow(ctx, lockSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Sku,
		&i.Region,
		&i.Status,
		&i.InstanceID,
		&i.PublicIp,
		&i.ErrorReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ReadyAt,
		&i.TerminatedAt,
	)
	return i, err
}

const setSessionError = `-- name: SetSessionError :exec
UPDATE sessions
SET status = 'error', error_reason = $2, updated_at = now()
WHERE id = $1
`

type SetSessionErrorParams struct {
	ID          string  `json:"id"`
	ErrorReason *string `json:"error_reason"`
}

func (q *Queries) SetSessionError(ctx context.Context, arg SetSessionErrorParams) error {
	_, err := q.db.Exec(ctx, setSessionError, arg.ID, arg.ErrorReason)
	return err
}

const setSessionReady = `-- name: SetSessionReady :exec
UPDATE sessions
SET status = 'ready', instance_id = $2, public_ip = $3, ready_at = now(), updated_at = now()
WHERE id = $1
`

type SetSessionReadyParams struct {
	ID         string  `json:"id"`
	InstanceID *string `json:"instance_id"`
	PublicIp   *string `json:"public_ip"`
}

func (q *Queries) SetSessionReady(ctx context.Context, arg SetSessionReadyParams) error {
	_, err := q.db.Exec(ctx, setSessionReady, arg.ID, arg.InstanceID, arg.PublicIp)
	return err
}

const setSessionStatus = `-- name: SetSessionStatus :exec
UPDATE sessions
SET status = $2, updated_at = now()
WHERE id = $1
`

type SetSessionStatusParams struct {
	ID     string        `json:"id"`
	Status SessionStatus `json:"status"`
}

func (q *Queries) SetSessionStatus(ctx context.Context, arg SetSessionStatusParams) error {
	_, err := q.db.Exec(ctx, setSessionStatus, arg.ID, arg.Status)
	return err
}

const setSessionTerminated = `-- name: SetSessionTerminated :exec
UPDATE sessions
SET status = 'terminated', terminated_at = now(), updated_at = now()
WHERE id = $1
`

func (q *Queries) SetSessionTerminated(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, setSessionTerminated, id)
	return err
}
