// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
)

const getUserByClerkSubject = `-- name: GetUserByClerkSubject :one
SELECT id, clerk_subject, email, created_at FROM users WHERE clerk_subject = $1
`

func (q *Queries) GetUserByClerkSubject(ctx context.Context, clerkSubject string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByClerkSubject, clerkSubject)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkSubject,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (clerk_subject, email)
VALUES ($1, $2)
ON CONFLICT (clerk_subject) DO UPDATE SET email = EXCLUDED.email
RETURNING id, clerk_subject, email, created_at
`

type UpsertUserParams struct {
	ClerkSubject string  `json:"clerk_subject"`
	Email        *string `json:"email"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, arg.ClerkSubject, arg.Email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ClerkSubject,
		&i.Email,
		&i.CreatedAt,
	)
	return i, err
}
